name: app_dancesp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgcapa.png
    - assets/imgQuemSomos.png
    - assets/imgmoHipHop.png
    - assets/imgmoBallet.png
    - assets/imgmoJazz.png
    - assets/grupHipHop.png
    - assets/millenium.png
    - assets/cyber.jpeg
    - assets/alexa.png
    - assets/Cybernetikos.png
    - assets/alexan2.jpg
    - assets/allegro.jpeg
    - assets/layllalobo.jpg
    - assets/alexan2.jpg
    - assets/allegro2.jpeg
    - assets/cisne.jpg
    - assets/cisnenegro2.jpg
    - assets/estudiol.jpg
    - assets/estudiol2.jpg
    - assets/layllalobo.jpg
    - assets/layllalobo2.jpg
    - assets/wa.png
    - assets/sam.jpg
    - assets/sam2.jpeg
    - assets/wa2.jpg
    - assets/semfoto.jpg